# Generated by Django 6.0.3 on 2026-03-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_ponto', models.ImageField(help_text='Foto destaque do ponto turístico', upload_to='fotos_dos_pontos/', verbose_name='Imagem principal')),
                ('imagem_1', models.ImageField(help_text='Primeira imagem complementar (ex: vista geral)', upload_to='fotos_dos_pontos/', verbose_name='Imagem ilustrativa 1')),
                ('imagem_2', models.ImageField(help_text='Segunda imagem complementar (ex: detalhe arquitetônico)', upload_to='fotos_dos_pontos/', verbose_name='Imagem ilustrativa 2')),
                ('imagem_3', models.ImageField(help_text='Terceira imagem complementar (ex: interior ou evento)', upload_to='fotos_dos_pontos/', verbose_name='Imagem ilustrativa 3')),
                ('imagem_4', models.ImageField(help_text='Quarta imagem complementar (ex: entorno ou acesso)', upload_to='fotos_dos_pontos/', verbose_name='Imagem ilustrativa 4')),
                ('titulo_ponto', models.CharField(max_length=200, verbose_name='Título do ponto turístico')),
                ('descricao_ponto', models.TextField(verbose_name='Descrição detalhada')),
                ('localizacao_ponto', models.CharField(max_length=300, verbose_name='Localização (cidade, bairro, endereço completo)')),
                ('servicos_prestados_ponto', models.TextField(verbose_name='Serviços oferecidos (guia, estacionamento, acessibilidade, etc.)')),
                ('horario_atendimento_ponto', models.CharField(max_length=200, verbose_name='Horário de funcionamento')),
                ('contacto_ponto', models.CharField(max_length=150, verbose_name='Contato (telefone, WhatsApp, e-mail)')),
                ('imagem_hotel', models.ImageField(help_text='Foto destaque do hotel', upload_to='fotos_dos_hoteeis/', verbose_name='Imagem principal')),
                ('titulo_hotel', models.CharField(max_length=200, verbose_name='Nome do hotel')),
                ('descricao_hotel', models.TextField(verbose_name='Descrição detalhada do hotel')),
                ('localizacao_hotel', models.CharField(max_length=300, verbose_name='Localização (cidade, bairro, endereço completo)')),
                ('servicos_prestados_hotel', models.TextField(verbose_name='Serviços oferecidos (guia, estacionamento, psina, etc.)')),
                ('horario_hotel', models.CharField(max_length=200, verbose_name='Horário de funcionamento')),
                ('contacto_hotel', models.CharField(max_length=150, verbose_name='Contato (telefone, WhatsApp, e-mail)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
