# Generated by Django 6.0.3 on 2026-03-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinel_administrativo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PontoTuristico',
        ),
    ]
