# Generated by Django 6.0.3 on 2026-05-09 03:56

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('nota', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('publicado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_ponto', models.ImageField(help_text='Foto destaque do ponto turístico', upload_to='fotos_dos_pontos/', verbose_name='Imagem principal')),
                ('imagem_1', models.ImageField(help_text='Primeira imagem complementar (ex: vista geral)', upload_to='fotos_dos_pontos/', verbose_name='Imagem ilustrativa 1')),
                ('imagem_2', models.ImageField(help_text='Segunda imagem complementar (ex: detalhe arquitetônico)', upload_to='fotos_dos_pontos/', verbose_name='Imagem ilustrativa 2')),
                ('imagem_3', models.ImageField(help_text='Terceira imagem complementar (ex: interior ou evento)', upload_to='fotos_dos_pontos/', verbose_name='Imagem ilustrativa 3')),
                ('imagem_4', models.ImageField(help_text='Quarta imagem complementar (ex: entorno ou acesso)', upload_to='fotos_dos_pontos/', verbose_name='Imagem ilustrativa 4')),
                ('titulo_ponto', models.CharField(max_length=200, verbose_name='Título do ponto turístico')),
                ('descricao_ponto', models.TextField(verbose_name='Descrição detalhada')),
                ('localizacao_ponto', models.CharField(max_length=300, verbose_name='Localização (cidade, bairro, endereço completo)')),
                ('servicos_prestados_ponto', models.TextField(verbose_name='Serviços oferecidos (guia, estacionamento, acessibilidade, etc.)')),
                ('horario_atendimento_ponto', models.CharField(max_length=200, verbose_name='Horário de funcionamento')),
                ('contacto_ponto', models.CharField(max_length=150, verbose_name='Contato (telefone, WhatsApp, e-mail)')),
                ('imagem_hotel', models.ImageField(help_text='Foto destaque do hotel', upload_to='fotos_dos_hoteeis/', verbose_name='Imagem principal')),
                ('titulo_hotel', models.CharField(max_length=200, verbose_name='Nome do hotel')),
                ('descricao_hotel', models.TextField(verbose_name='Descrição detalhada do hotel')),
                ('localizacao_hotel', models.CharField(max_length=300, verbose_name='Localização (cidade, bairro, endereço completo)')),
                ('servicos_prestados_hotel', models.TextField(verbose_name='Serviços oferecidos (guia, estacionamento, psina, etc.)')),
                ('horario_hotel', models.CharField(max_length=200, verbose_name='Horário de funcionamento')),
                ('contacto_hotel', models.CharField(max_length=150, verbose_name='Contato (telefone, WhatsApp, e-mail)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='praias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_praia', models.ImageField(upload_to='fotos_das_praias/', verbose_name='Imagem principal')),
                ('titulo_praia', models.CharField(max_length=200, verbose_name='Nome da práia')),
                ('descricao_praia', models.TextField(verbose_name='Descrição detalhada')),
                ('localizacao_ponto', models.CharField(max_length=300, verbose_name='Localização (cidade, bairro, endereço completo)')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPER_ADMIN', 'Super Admin')], default='ADMIN', help_text='Define se é Administrador ou Super Admin', max_length=20, verbose_name='Tipo de usuário')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o usuário está ativo no sistema', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('excluido', models.BooleanField(default=False, help_text='Soft delete - marca como excluído sem remover do banco', verbose_name='Excluído')),
                ('data_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de exclusão')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['email'], name='global_mode_email_6d0509_idx'), models.Index(fields=['tipo'], name='global_mode_tipo_eab1ed_idx'), models.Index(fields=['ativo'], name='global_mode_ativo_4a5bc6_idx')],
            },
        ),
    ]
