# Generated by Django 6.0.3 on 2026-07-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praias',
            name='localizacao_ponto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Localização (cidade, bairro, endereço completo)'),
        ),
    ]
