"""
Django settings for Belas_Projecto project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Carrega as variáveis do arquivo .env se estiver rodando localmente
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SEGURANÇA: Usa a chave do ambiente no Render; se local, usa a sua antiga chave padrão
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-=ausnn^u+lgj+@(g=f!bn&oof(zw#vvaqmessw+e2zlf%r6u@g')

# SEGURANÇA: Fica False em produção automaticamente se a variável de ambiente for configurada
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Configuração de hosts permitidos (adicionado suporte ao Render e domínios locais)
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', '*'] 

# Mantido as origens confiáveis para o CSRF
CSRF_TRUSTED_ORIGINS = ['https://api.ngrok.com']


# Application definition

INSTALLED_APPS = [
    # O cloudinary_storage DEVE obrigatoriamente ficar acima do staticfiles
    'cloudinary_storage',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Aplicações do seu TCC
    'Aplicativo_Belas',
    'pinel_administrativo',
    'global_models',
    
    # Biblioteca base do Cloudinary
    'cloudinary',
]

# Modelo personalizado de usuário do seu TCC
AUTH_USER_MODEL = 'global_models.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir HTML/CSS/JS estáticos em produção
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Belas_Projecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Belas_Projecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Se houver a variável DATABASE_URL (no Render), ele se conecta ao banco de produção.
# Caso contrário (ambiente local), ele usa os dados do seu banco PostgreSQL local 'banco_turismo_belas'.
DATABASES = {
    'default': dj_database_url.config(
        default='postgres://postgres:0000@localhost:6126/banco_turismo_belas',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Diretório para onde o Django jogará todos os arquivos estáticos unificados em produção
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Onde o Django busca os arquivos estáticos durante o desenvolvimento.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Aplicativo_Belas', 'static'),
]


# Configurações de Mídia (Uploads de imagens)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Configurações de Armazenamento e Integrações (Cloudinary e WhiteNoise)

# Credenciais do Cloudinary com leitura segura do ambiente e fallback para o seu local
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', 'turismoImagens'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '752713951376889'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', 't3SnQ08x_jSQRrdNXPKO9xTzf6U'),
}

# Configuração unificada de Backends para Django 6.x
STORAGES = {
    # Controla o upload de mídias direto para o Cloudinary
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    # Controla o cache e compressão dos arquivos estáticos com o WhiteNoise
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Regra de tolerância para o WhiteNoise (Impede falhas de build por falta de arquivos do Admin)
WHITENOISE_MANIFEST_STRICT = False

# Retrocompatibilidade exigida internamente pela biblioteca django-cloudinary-storage
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"